name: Trivy Scanner
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  dotnet:
    name: .NET Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          scan-ref: "./CSETWebApi"
          severity: "CRITICAL,HIGH"
  nodejs:
    name: Node.js Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          scan-ref: "./CSETWebNg"
          format: "sarif"
          output: "trivy-nodejs-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-nodejs-results.sarif"
